### ISSUE TITLE
will cause electron stuck when pasting in linux platform

### ISSUE THREAD

**Issue by TheoXiong** [arjun-g/electron-clipboard-extended#3]
I require this module at the top of main.js for main process.
    I copy any word and paste into electron's input field, then the interface of electron become unresponsive.
    It just happened on linux platform, and there is no problem on windows or mac.
    I guess that's probably because the clipboard cannot be used befor app ready.
    I require this module after main window ready, it won't happen.

    `mainWindow.once('ready-to-show', () => {
       mainWindow.show()      
       const clipboard = require('electron-clipboard-extended')
       clipboard
         .on('text-changed', () => { /* do something */ })
         .startWatching()   
    })`

**Comment by Noitidart** [comment]
Very interesting, thanks for sharing this. So I can work around this by placing this code in `ready-to-show` in main process?

**Comment by TheoXiong** [comment]
That solution can solve my problem very well.

There's another way to solve this,  may be you can initialize previousText/previousImage with empty string(in line 5), it will read clipboard  for the first time after startWatching, and app is ready at that time because there is 500 millisecond delay.

It's just my test result，you can reconfirm it.

**Comment by Noitidart** [comment]
Very interesting thanks for sharing! I actually am not using this module anymore, but if I do I'll this out and let you know.

**Comment by Noitidart** [comment]
This is an important note, so maybe rather then just closing this, we should document clearly that we they should not use this until `app.on('ready')`?

**Comment by TheoXiong** [comment]
Yes, it would be better if add some notes about this.
